### PR TITLE
Do not free unowned record handles

### LINKED ISSUE #519: Running GLib-2.0 tests fails on fedora 35 via dotnet commandline
- Running GLib-2.0 tests fails on fedora 35 via dotnet commandline
- The tests run fine inside Rider.
- Tests run fine on github actions

Run: ` dotnet test Tests/Libs/GLib-2.0.Tests/`

```
The active test run was aborted. Reason: Test host process crashed : (process:12477): GLib-CRITICAL **: 07:16:20.902: g_atomic_ref_count_dec: assertion 'old_value > 0' failed
(process:12477): GLib-CRITICAL **: 07:16:20.902: g_atomic_ref_count_dec: assertion 'old_value > 0' failed
(process:12477): GLib-CRITICAL **: 07:16:20.902: g_atomic_ref_count_dec: assertion 'old_value > 0' failed
Unhandled exception. System.Exception: Can't free native handle of type "GLib.Internal.Dir".
   at GLib.Internal.Dir.Handle.ReleaseHandle() in /mnt/daten/Programmierung/CSharp/GirCore/gir.core/src/Libs/GLib-2.0/Internal/Records/Dir.SafeHandle.Generated.cs:line 27
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation) in /builddir/build/BUILD/dotnet-9e8b04bbff820c93c142f99a507a46b976f5c14c/src/runtime.4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 249
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing) in /builddir/build/BUILD/dotnet-9e8b04bbff820c93c142f99a507a46b976f5c14c/src/runtime.4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 98
   at System.Runtime.InteropServices.SafeHandle.Finalize() in /builddir/build/BUILD/dotnet-9e8b04bbff820c93c142f99a507a46b976f5c14c/src/runtime.4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 72


Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte() in /builddir/build/BUILD/dotnet-9e8b04bbff820c93c142f99a507a46b976f5c14c/src/runtime.4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/IO/BinaryReader.cs:line 207
   at System.IO.BinaryReader.Read7BitEncodedInt() in /builddir/build/BUILD/dotnet-9e8b04bbff820c93c142f99a507a46b976f5c14c/src/runtime.4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/IO/BinaryReader.cs:line 611
   at System.IO.BinaryReader.ReadString() in /builddir/build/BUILD/dotnet-9e8b04bbff820c93c142f99a507a46b976f5c14c/src/runtime.4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/IO/BinaryReader.cs:line 270
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
```

We probably need to fine tune the safe handle generation a bit more. The `Dir` handle is transfered without ownership. So we are not allowed to free it. Actually we cant free it: This is why we raise an exception.

For some reason the dotnet runtime does not try to free the memory before test execution stops in rider / github actions. See #525 

This is currently only relevant for records as objects do not use safe handles.

### PR DESCRIPTION
**Pull request by badcel**
Fixes #519

### CODE REVIEW

**Comment by badcel** [comment]
Possible implementation for Record based SafeHandles:

```CS
public abstract class DirHandle : SafeHandle
{
    protected DirHandle(bool ownsHandle) : base(IntPtr.Zero, ownsHandle) { }
    
    public sealed override bool IsInvalid => handle == IntPtr.Zero;
}

public partial class NullDirHandle : DirHandle
{
    public static NullDirHandle Instance = new NullDirHandle();
    
    private NullDirHandle() : base(true) { }
    
    protected override bool ReleaseHandle()
    {
        throw new System.Exception("It is not allowed to free a handle of type \"GLib.Internal.NullDirHandle\".");
    }
}

public partial class OwnedDirHandle : DirHandle
{
    private OwnedDirHandle() : base(true) {}
    
    protected override bool ReleaseHandle()
    {
        throw new System.Exception("Can't free native handle of type \"GLib.Internal.DirHandle\".");
    }
}

public partial class UnownedDirHandle : DirHandle
{
    private UnownedDirHandle() : base(false) {}
    
    protected override bool ReleaseHandle()
    {
        throw new System.Exception("It is not allowed to free handle of type \"GLib.Internal.UnownedDirHandle\".");
    }
}

public partial class ManagedDirHandle : DirHandle
{
    public static DirHandle Create(DirData? data = null)
    {
        var size = Marshal.SizeOf<DirData>();
        IntPtr ptr = Marshal.AllocHGlobal(size);
            
        if (data.HasValue)
        {
            Marshal.StructureToPtr(data.Value, ptr, false);
        }
        else
        {
            var str = new DirData();
            Marshal.StructureToPtr(str, ptr, false);
        }
            
        return new ManagedDirHandle(ptr);
    }

    private ManagedDirHandle(IntPtr handle) : base(true)
    {
        SetHandle(handle);
    }

    protected override bool ReleaseHandle()
    {
        Marshal.FreeHGlobal(handle);
        return true;
    }
}
```

File: src/Generation/Generator3/Generation/Record/PublicClass/PublicClassModel.cs [hunk 1]
```diff
@@ -8,6 +8,8 @@ public class PublicClassModel
 
         public string Name => _record.GetPublicClassName();
         public string InternalHandleName => _record.GetInternalHandleName();
+        public string InternalOwnedHandleName => _record.GetInternalOwnedHandleName();
```
Comment (badcel) [inline src/Generation/Generator3/Generation/Record/PublicClass/PublicClassModel.cs:11]: Not used?

**Review by badcel — COMMENTED** [review]
One remark
